name: "PartL Monitor — Crawl & Publish"

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}
  schedule:
    - cron: "17 7 * * 1"   # Mondays 07:17 London

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare output folders
        run: |
          mkdir -p docs docs/archive docs/diffs history texts archive diffs registry

      - name: Crawl (write registry/current.json)
        run: |
          python scripts/check_partl.py --rules rules --out registry/current.json --debug

      # ➜ Add a timestamp so the UI can show "Checked"
      - name: Stamp checked_at on results
        env:
          JSON_PATH: registry/current.json
        run: |
          python - <<'PY'
import json, os, datetime
p = os.environ['JSON_PATH']
with open(p, 'r', encoding='utf-8') as f:
    data = json.load(f)
now = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'
items = data.get('items', data)
for row in items:
    row['checked_at'] = now
if isinstance(data, dict) and 'items' in data:
    data['items'] = items
else:
    data = items
with open(p, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f'Stamped {len(items)} items at {now}')
PY

      # ➜ Generate PDF thumbnails (uses Poppler's pdftoppm)
      - name: Install Poppler (for pdftoppm)
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Generate PDF thumbnails (writes docs/thumbs & updates registry/current.json)
        env:
          OUT_DIR: docs                    # thumbnails placed here for Pages
          JSON_PATH: registry/current.json # enriches this JSON with thumb_url
        run: |
          python scripts/make_thumbs.py    # (you already have this file in scripts/)

      - name: Render static site (to docs/)
        run: |
          python scripts/render_site.py --registry registry/current.json --templates templates --out docs

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
