name: Monitor Energy Docs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"  # Mondays 05:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python & pip
        run: |
          python -V
          python -m pip -V

      - name: Upgrade pip tooling
        run: python -m pip install -U pip setuptools wheel

      # Try to use a prebuilt lxml wheel; if not available, install build deps and retry
      - name: Install Python deps (with lxml fallback)
        run: |
          set -e
          python -m pip install --only-binary=:all: "lxml<6,>=4.9" || (
            sudo apt-get update &&
            sudo apt-get install -y libxml2-dev libxslt1-dev python3-dev &&
            python -m pip install "lxml<6,>=4.9"
          )
          python -m pip install requests beautifulsoup4 pdfminer.six Jinja2

      - name: Run monitor (never fail the job)
        run: |
          python scripts/check_partl.py || echo "::warning::check_partl.py failed (continuing)"
          python scripts/render_site.py || echo "::warning::render_site.py failed (continuing)"

      - name: Stage site to docs/
        run: |
          mkdir -p docs/archive docs/diffs
          cp -r archive/* docs/archive/ 2>/dev/null || true
          cp -r diffs/*   docs/diffs/   2>/dev/null || true
          ls -la docs || true

      - name: Commit updates to repo
        run: |
          git config user.email "regs-bot@users.noreply.github.com"
          git config user.name  "regs-bot"
          git add registry history archive diffs texts docs CHANGELOG.md || true
          git commit -m "Update registry, history, and site" || echo "No changes"
          git push || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
